"""
Curriculum graph for the Mastery Hub (mastery_server.py, port 5001).

Every topic here maps to a file that already exists on disk (served today by
server.py on port 5000). This module adds no new content — it adds ordering
(tiers, easiest first), cross-links (related topics across the old silos:
NCA-GENL / BNSF interview prep / DS fundamentals / practice docs), and a
place to hang per-topic mastery progress.

kind:
  "md"    -> rendered through doc_template.html via markdown, same as server.py's /doc/<slug>
  "html"  -> an existing self-contained interactive guide, served as-is
"""

TIERS = [
    {
        "id": -1,
        "name": "Reference",
        "subtitle": "Not a rung on the ladder — the module/one-line-command lookup you keep open in a tab while working through every tier below",
        "is_reference": True,
    },
    {
        "id": "bonus-drills",
        "name": "Code Drills",
        "subtitle": "Optional, self-paced — 378 question-then-code-answer reps from x = 5 through tuning an LSTM to a full LangGraph tool-calling agent. Not required for the ladder below; start here if Python itself feels rusty.",
        "is_bonus": True,
    },
    {
        "id": 0,
        "name": "Foundations",
        "subtitle": "Data & math substrate — everything above depends on this",
    },
    {
        "id": 1,
        "name": "Core ML & Problem Framing",
        "subtitle": "Classical models, how to frame a problem, the LLM map",
    },
    {
        "id": 2,
        "name": "Deep Learning & Transformers",
        "subtitle": "Neural nets, PyTorch/TF internals, the full transformer + NCA-GENL exam",
    },
    {
        "id": 3,
        "name": "LLM Systems & Applied Engineering",
        "subtitle": "RAG, agents, fine-tuning/serving at scale, applied to the freight-rail domain",
    },
    {
        "id": 4,
        "name": "MLOps & Production",
        "subtitle": "Shipping and operating what you built — tracking, versioning, serving, monitoring",
    },
    {
        "id": 5,
        "name": "Interview Performance & Synthesis",
        "subtitle": "Putting it all together under time pressure and in a room with people",
    },
]

TOPICS = [
    # ---------------- Tier -1: Reference (outside the ladder) ----------------
    {"id": "module-cheatsheet", "title": "Module & One-Line Command Cheat Sheet", "tier": -1, "kind": "md",
     "file": "module-cheatsheet.md",
     "blurb": "94 entries: task → exact module path → one-line call, for ML/NN/CNN/RNN/LSTM/LLM/optimization/training/inferencing. A lookup tool, not a tier to finish.",
     "related": ["practice-sklearn", "practice-pytorch-deep", "practice-deep-learning", "nca-genl",
                 "core-technical", "practice-langchain", "live-coding", "code-drills-classical-ml", "code-drills-deep-learning",
                 "code-drills-llm-huggingface", "code-drills-finetuning-peft"]},
    {"id": "common-issues", "title": "Common Issues & Failure Modes", "tier": -1, "kind": "md",
     "file": "common-issues-failure-modes.md",
     "blurb": "What breaks and why, across classical ML, deep learning, LLM/RAG, and production — the reference you check when something's wrong, not before.",
     "related": ["ds-fundamentals", "practice-pytorch-deep", "rag-deeper", "production-ml", "practice-sklearn",
                 "practice-stats", "time-series", "real-world-incidents"]},
    {"id": "real-world-incidents", "title": "Real-World Incidents & Wins", "tier": -1, "kind": "md",
     "file": "real-world-incidents.md",
     "blurb": "Documented, dated, sourced case studies with real company names and numbers — prompt-injection attacks, latency outages, correctness failures after scale/drift, agentic-loop failures (AutoGPT, a $47K LangChain loop, Replit's deleted database), plus performance and accuracy wins (vLLM, LoRA, AlexNet, AlphaFold).",
     "related": ["system-design", "common-issues", "core-technical", "agent-decision-loop"]},
    {"id": "git-scenarios", "title": "Git Commands for Real Scenarios", "tier": -1, "kind": "md",
     "file": "git-scenarios-cheatsheet.md",
     "blurb": "Lookup by situation — conflicts, rebase, bisect, undoing history, LFS for model files, plus how teams actually work on GitHub: PRs, forks, CODEOWNERS, branch protection, merge queues, hotfixes, merge-commit vs squash vs rebase — not a git tutorial.",
     "related": ["mlops-practice", "live-coding", "git-sim"]},
    {"id": "git-sim", "title": "Git Simulator — Multi-User Sandbox", "tier": -1, "kind": "html",
     "route": "/git-sim",
     "blurb": "A real sandboxed git repo plus a scripted teammate — type actual git commands, trigger the teammate's push whenever you want, and hit genuine fast-forwards, merge conflicts, and force-push races. Local only (mastery_server.py, port 5001).",
     "related": ["git-scenarios"]},

    # ---------------- Bonus Tier: Code Drills (optional, outside the ladder) ----------------
    {"id": "code-drills-basics", "title": "Code Drills 1 — Basics (Variables, Strings, Control Flow, Functions)", "tier": "bonus-drills", "kind": "md",
     "file": "code-drills-basics.md",
     "blurb": "~65 question-then-code reps: variables/types, string ops (split/join/slice), if/for/while, functions incl. *args/**kwargs and closures. Start here if raw Python syntax feels shaky.",
     "related": ["code-drills-data-structures", "practice-utilities"]},
    {"id": "code-drills-data-structures", "title": "Code Drills 2 — Data Structures, JSON, Files, Exceptions", "tier": "bonus-drills", "kind": "md",
     "file": "code-drills-data-structures.md",
     "blurb": "~55 reps: lists/dicts/sets/comprehensions, the literal 'how do I turn JSON into a dict' question, file I/O, try/except.",
     "related": ["code-drills-basics", "code-drills-oop", "practice-utilities"]},
    {"id": "code-drills-oop", "title": "Code Drills 3 — OOP, Decorators, Generators, Context Managers", "tier": "bonus-drills", "kind": "md",
     "file": "code-drills-oop-intermediate.md",
     "blurb": "~31 reps on classes/inheritance/@property, decorators, generators/yield, and custom context managers — drill #15 draws the direct line from a plain Python class to nn.Module.",
     "related": ["code-drills-data-structures", "code-drills-numpy-pandas", "practice-pytorch-deep"]},
    {"id": "code-drills-numpy-pandas", "title": "Code Drills 4 — NumPy & Pandas", "tier": "bonus-drills", "kind": "md",
     "file": "code-drills-numpy-pandas.md",
     "blurb": "40 reps: array/DataFrame mechanics as quick-fire Q-then-code. Terser companion to the full numpy-practice.md/pandas-practice.md narrative deep dives.",
     "related": ["code-drills-oop", "code-drills-classical-ml", "practice-numpy", "practice-pandas"]},
    {"id": "code-drills-classical-ml", "title": "Code Drills 5 — Classical ML (train/eval RandomForest & friends)", "tier": "bonus-drills", "kind": "md",
     "file": "code-drills-classical-ml.md",
     "blurb": "28 reps covering the full sklearn workflow — split, train a RandomForest, evaluate, tune with GridSearchCV, save/load. Direct answer to 'how do I train and evaluate a RandomForest.'",
     "related": ["code-drills-numpy-pandas", "code-drills-deep-learning", "practice-ml-models", "practice-sklearn", "module-cheatsheet"]},
    {"id": "code-drills-deep-learning", "title": "Code Drills 6 — PyTorch: Tensors, Training Loops, CNNs, LSTM Tuning", "tier": "bonus-drills", "kind": "md",
     "file": "code-drills-deep-learning.md",
     "blurb": "48 reps: autograd, the 4-line training loop, building/training a CNN, and the LSTM hyperparameter-tuning cluster (hidden_size, num_layers, LR, gradient clipping, batch_size).",
     "related": ["code-drills-classical-ml", "code-drills-llm-huggingface", "practice-deep-learning", "practice-pytorch-deep", "module-cheatsheet"]},
    {"id": "code-drills-llm-huggingface", "title": "Code Drills 7 — LLMs: Tokenization, HuggingFace, Decoding, Embeddings", "tier": "bonus-drills", "kind": "md", "role": "ai_engineer",
     "file": "code-drills-llm-huggingface.md",
     "blurb": "36 reps: real gpt2 tokenization/generation, greedy vs. sampled vs. beam decoding, temperature/top-k/top-p compared directly, and sentence embeddings for semantic search — verified against real downloaded models.",
     "related": ["code-drills-deep-learning", "code-drills-rag-langchain", "llm-landscape", "nca-genl", "module-cheatsheet"]},
    {"id": "code-drills-rag-langchain", "title": "Code Drills 8 — RAG & LangChain: Chunking to a Full Grounded Pipeline", "tier": "bonus-drills", "kind": "md", "role": "ai_engineer",
     "file": "code-drills-rag-langchain.md",
     "blurb": "20 reps: chunking tradeoffs, a real FAISS index, wiring a local embedder into LangChain, and a full LCEL RAG chain making real calls to this project's Azure deployment — includes a drill showing grounding actually refuse an out-of-context question.",
     "related": ["code-drills-llm-huggingface", "code-drills-finetuning-peft", "practice-langchain", "rag-deeper", "core-technical"]},
    {"id": "code-drills-finetuning-peft", "title": "Code Drills 9 — Fine-Tuning: LoRA, QLoRA, PEFT, the Trainer API", "tier": "bonus-drills", "kind": "md", "role": "ai_engineer",
     "file": "code-drills-finetuning-peft.md",
     "blurb": "26 reps: a real LoRA adapter trained on distilgpt2 end to end (real decreasing loss, base weights proven untouched), QLoRA's quantization config, and SFTTrainer — the run-it-yourself layer under core-technical-depth.md's LoRA arithmetic.",
     "related": ["code-drills-rag-langchain", "code-drills-langgraph-agents", "core-technical", "practice-pytorch-deep", "module-cheatsheet"]},
    {"id": "code-drills-langgraph-agents", "title": "Code Drills 10 — LangGraph: StateGraph, Tool-Calling Agents, Memory", "tier": "bonus-drills", "kind": "md", "role": "ai_engineer",
     "file": "code-drills-langgraph-agents.md",
     "blurb": "28 reps: conditional edges, a real cyclic retry graph with a recursion-limit safety net, a full ReAct tool-calling agent against a real LLM, and thread-isolated conversation memory — closes the Code Drills tier.",
     "related": ["code-drills-finetuning-peft", "practice-langgraph", "system-design"]},

    # ---------------- Tier 0: Foundations ----------------
    {"id": "practice-numpy", "title": "NumPy Practice", "tier": 0, "kind": "md",
     "file": "numpy-practice.md",
     "blurb": "Array mechanics, broadcasting, vectorization — the substrate everything else in Python DS sits on.",
     "related": ["practice-pandas", "practice-ml-models", "live-coding", "module-cheatsheet", "code-drills-numpy-pandas"]},
    {"id": "practice-pandas", "title": "Pandas Practice", "tier": 0, "kind": "md",
     "file": "pandas-practice.md",
     "blurb": "DataFrame wrangling, groupby, joins — the day-to-day tool for shaping data before modeling.",
     "related": ["practice-numpy", "practice-visualization", "practice-stats", "live-coding", "leetcode-pandas", "code-drills-numpy-pandas"]},
    {"id": "practice-stats", "title": "Statistics (SciPy/statsmodels) Practice", "tier": 0, "kind": "md",
     "file": "stats-scipy-practice.md",
     "blurb": "Distributions, hypothesis tests, p-values — the rigor behind 'is this difference real.'",
     "related": ["practice-pandas", "service-impact", "ds-fundamentals", "practice-ml-models",
                 "common-issues", "math-foundations", "leetcode-stats-probability", "time-series"]},
    {"id": "practice-utilities", "title": "Python Utilities Practice", "tier": 0, "kind": "md",
     "file": "python-utilities-practice.md",
     "blurb": "datetime/regex/I-O/performance idioms — the small stuff that live coding rounds quietly test.",
     "related": ["live-coding", "practice-pandas", "code-drills-basics", "code-drills-data-structures"]},
    {"id": "ds-fundamentals", "title": "Data Science Fundamentals — Pictorial", "tier": 0, "kind": "html",
     "route": "/m/ds-fundamentals",
     "blurb": "Gradient descent, loss functions, bias-variance, L1/L2 regularization — worked by hand, with diagrams.",
     "related": ["nca-genl", "practice-deep-learning", "practice-ml-models", "math-foundations"]},
    {"id": "practice-visualization", "title": "Data Visualization Practice", "tier": 0, "kind": "md",
     "file": "visualization-practice.md",
     "blurb": "Choosing and building the right chart — matplotlib/seaborn mechanics for telling the data's story.",
     "related": ["practice-pandas", "service-impact"]},
    {"id": "sql-practice", "title": "SQL Practice", "tier": 0, "kind": "md",
     "file": "sql-practice.md",
     "blurb": "Joins, GROUP BY/HAVING, window functions, CTEs, indexing — how data actually gets to you before pandas touches it.",
     "related": ["practice-pandas", "practice-stats", "live-coding", "leetcode-sql", "practice-data-engineering"]},
    {"id": "practice-data-engineering", "title": "Data Engineering Practice", "tier": 0, "kind": "md",
     "file": "data-engineering-practice.md",
     "blurb": "Star schemas, slowly changing dimensions, ETL vs. ELT, batch vs. streaming, DAGs, data quality, partitioning — the layer above SQL that decides what you're even querying.",
     "related": ["sql-practice", "mlops-practice", "production-ml", "system-design", "practice-pandas"]},
    {"id": "math-foundations", "title": "Math Foundations Refresher", "tier": 0, "kind": "md",
     "file": "math-foundations-refresher.md",
     "blurb": "Linear algebra and probability, worked with small real numbers — the math every other doc here quietly assumes.",
     "related": ["ds-fundamentals", "practice-numpy", "practice-stats", "nca-genl", "nn-numericals"]},
    {"id": "nn-numericals", "title": "Neural Net Numericals (Forward/Backward Pass, Loss, Weight Updates)", "tier": 0, "kind": "md",
     "file": "neural-net-numerical-practice.md",
     "blurb": "A toy network worked entirely in real numbers — forward pass, loss, backprop by hand, weight update, epochs/iterations, shapes — then a 20-MCQ drill.",
     "related": ["math-foundations", "practice-deep-learning", "practice-pytorch-deep", "nca-genl"]},

    # ---------------- Tier 1: Core ML & Problem Framing ----------------
    {"id": "practice-sklearn", "title": "scikit-learn Practice", "tier": 1, "kind": "md",
     "file": "sklearn-practice.md",
     "blurb": "Pipelines, cross-validation, the standard fit/predict API most classical models share.",
     "related": ["practice-ml-models", "practice-numpy", "practice-stats", "module-cheatsheet", "code-drills-classical-ml"]},
    {"id": "practice-ml-models", "title": "Classical ML Models Practice", "tier": 1, "kind": "md",
     "file": "ml-models-practice.md",
     "blurb": "One question at a time on trees, boosting, linear/logistic regression, clustering — how and when each works.",
     "related": ["practice-sklearn", "practice-stats", "ds-fundamentals", "problem-formulation", "code-drills-classical-ml"]},
    {"id": "problem-formulation", "title": "Problem Formulation Framework", "tier": 1, "kind": "md",
     "file": "problem-formulation-framework.md",
     "blurb": "Turning a vague business ask into a well-posed ML problem — the meta-skill every other round assumes.",
     "related": ["system-design", "service-impact", "domain-context"]},
    {"id": "llm-landscape", "title": "LLM Landscape", "tier": 1, "kind": "md", "role": "ai_engineer",
     "file": "llm-landscape.md",
     "blurb": "25 open/closed-source models and what each is actually for — the map you need before any LLM-systems topic.",
     "related": ["nca-genl", "core-technical", "practice-langchain", "code-drills-llm-huggingface", "ai-engineer-playbook"]},
    {"id": "time-series", "title": "Time Series Analysis", "tier": 1, "kind": "md",
     "file": "time-series-analysis.md",
     "blurb": "Trend/seasonality decomposition, stationarity, ACF/PACF, ARIMA, and why forecasts must be evaluated chronologically, not randomly.",
     "related": ["practice-stats", "practice-pandas", "practice-ml-models", "common-issues"]},

    # ---------------- Tier 2: Deep Learning & Transformers ----------------
    {"id": "practice-deep-learning", "title": "Deep Learning Practice (RNN/LSTM/CNN, PyTorch)", "tier": 2, "kind": "md",
     "file": "deep-learning-practice.md",
     "blurb": "Neural net basics in PyTorch — the bridge from classical ML to sequence/vision architectures.",
     "related": ["ds-fundamentals", "practice-pytorch-deep", "nca-genl", "module-cheatsheet", "code-drills-deep-learning"]},
    {"id": "practice-pytorch-deep", "title": "PyTorch Deep Dive", "tier": 2, "kind": "md",
     "file": "pytorch-deep-dive.md",
     "blurb": "Hooks, mixed precision, DDP, GANs, ONNX export — the framework internals behind production training.",
     "related": ["practice-deep-learning", "core-technical", "nca-genl", "module-cheatsheet", "code-drills-deep-learning"]},
    {"id": "practice-tf-keras-deep", "title": "TensorFlow/Keras Deep Dive", "tier": 2, "kind": "md",
     "file": "tensorflow-keras-deep-dive.md",
     "blurb": "Custom layers, GradientTape, transfer learning — the same concepts as PyTorch, different API surface.",
     "related": ["practice-deep-learning", "practice-pytorch-deep"]},
    {"id": "nca-genl", "title": "NCA-GENL Study Guide — 7 Days to Certified", "tier": 2, "kind": "html", "role": "ai_engineer",
     "route": "/m/nca-genl",
     "blurb": "The full transformer teardown with real numbers, plus prompting/RAG, evaluation metrics, and trustworthy AI — internally ordered easy→hard across its own 7-day plan.",
     "related": ["ds-fundamentals", "core-technical", "bnsf-visual", "llm-landscape", "module-cheatsheet"]},

    # ---------------- Tier 3: LLM Systems & Applied Engineering ----------------
    {"id": "core-technical", "title": "Core Technical Depth", "tier": 3, "kind": "md", "role": "ai_engineer",
     "file": "core-technical-depth.md",
     "blurb": "LoRA/QLoRA, RAG internals, DDP, quantization, VRP/MILP optimization, skills/on-demand context loading — implementation-level, not exam-level.",
     "related": ["nca-genl", "practice-pytorch-deep", "practice-langchain", "domain-context", "module-cheatsheet", "code-drills-finetuning-peft", "ai-engineer-playbook"]},
    {"id": "practice-langchain", "title": "LangChain Practice", "tier": 3, "kind": "md", "role": "ai_engineer",
     "file": "langchain-practice.md",
     "blurb": "LCEL, RAG pipelines, tool-calling agents, and where each piece breaks in practice.",
     "related": ["practice-langgraph", "nca-genl", "llm-landscape", "module-cheatsheet", "code-drills-rag-langchain"]},
    {"id": "practice-langgraph", "title": "LangGraph Practice", "tier": 3, "kind": "md", "role": "ai_engineer",
     "file": "langgraph-practice.md",
     "blurb": "StateGraph, multi-step agents, checkpointing — orchestration once a single chain isn't enough.",
     "related": ["practice-langchain", "system-design", "code-drills-langgraph-agents", "footprint-case-file", "agent-decision-loop", "unified-telemetry-agent-design"]},
    {"id": "bnsf-visual", "title": "BNSF Technical Deep-Dive — Pictorial", "tier": 3, "kind": "html",
     "route": "/m/bnsf-visual",
     "blurb": "Optimization, geospatial, vector DBs, RAG/CoT/eval, GPU — same interactive diagram style as the transformer guide.",
     "related": ["nca-genl", "core-technical", "domain-context"]},
    {"id": "domain-context", "title": "Freight Rail AI Domain Context", "tier": 3, "kind": "md",
     "file": "freight-rail-ai-domain-context.md",
     "blurb": "The real use-case categories (hot-bearing detection etc.) — grounding for a domain you haven't worked in yet.",
     "related": ["problem-formulation", "service-impact", "core-technical"]},
    {"id": "service-impact", "title": "Service Impact & Causal Inference", "tier": 3, "kind": "md",
     "file": "service-impact-and-causal-inference.md",
     "blurb": "Proving an ML system actually moved a business metric — the causal-inference layer above plain statistics.",
     "related": ["problem-formulation", "practice-stats", "domain-context"]},
    {"id": "rag-deeper", "title": "RAG, Deeper (Advanced Retrieval & Knowledge Graphs)", "tier": 3, "kind": "md", "role": "ai_engineer",
     "file": "rag-deeper.md",
     "blurb": "Hybrid search, re-ranking, HyDE, multi-hop, RAGAS evaluation, GraphRAG/knowledge graphs — what makes basic RAG actually reliable.",
     "related": ["core-technical", "practice-langchain", "nca-genl", "common-issues", "code-drills-rag-langchain", "unified-telemetry-agent-design", "ai-engineer-playbook"]},
    {"id": "prompt-engineering-deeper", "title": "Prompt Engineering, Deeper", "tier": 3, "kind": "md", "role": "ai_engineer",
     "file": "prompt-engineering-deeper.md",
     "blurb": "Tree-of-Thought, Reflexion, DSPy-style optimization, structured output, prompt-injection defense — past zero-shot/CoT basics.",
     "related": ["nca-genl", "practice-langgraph", "rag-deeper", "ai-engineer-playbook"]},
    {"id": "ai-engineer-playbook", "title": "The AI Engineer Playbook — Tool-Named Interview Answers", "tier": 3, "kind": "md", "role": "ai_engineer",
     "file": "ai-engineer-playbook.md",
     "blurb": "62 interview questions across a hiring-manager checklist, LLM infra, RAG, prompt engineering, MLOps, and Python/backend — every one answered with the exact library and flag, not the category name. Plus 7 optimization techniques, a 10-step roadmap, and 10 papers worth reading.",
     "related": ["llm-landscape", "core-technical", "rag-deeper", "prompt-engineering-deeper", "mlops-practice", "production-ml", "system-design", "practice-langchain"]},
    {"id": "footprint-case-file", "title": "The Case File: How footprintjs Traces an AI's Decision — Pictorial", "tier": 3, "kind": "html", "role": "ai_engineer",
     "route": "/m/footprint-case-file",
     "blurb": "How Sanjay Krishna Anbalagan's open-source footprintjs/agentfootprint makes an agent's decisions traceable and provable — one real loan-rejection trace, walked backward, with diagrams.",
     "related": ["agent-decision-loop", "system-design-drills", "practice-langgraph", "rag-deeper"]},
    {"id": "agent-decision-loop", "title": "The Agent Decision Loop — Where It Actually Breaks (Pictorial)", "tier": 3, "kind": "html", "role": "ai_engineer",
     "route": "/m/agent-decision-loop",
     "blurb": "Six real, sourced production incidents (AutoGPT, a $47K LangChain loop, Replit's deleted database, Amazon Q's stale wiki, a supply-chain prompt injection) mapped to the exact stage of an agent's decision loop that failed.",
     "related": ["footprint-case-file", "real-world-incidents", "system-design-drills", "practice-langgraph", "code-drills-langgraph-agents"]},
    {"id": "unified-telemetry-agent-design", "title": "Unifying App, Infra & Analytics Logs for an LLM Agent (Pictorial)", "tier": 3, "kind": "html", "role": "ai_engineer",
     "route": "/m/unified-telemetry-agent-design",
     "blurb": "A real engineering design for context/token budgeting, vocabulary normalization, memory-as-state, and hypothesis-driven tool selection — sourced to Honeycomb's Query Assistant and Datadog's Bits AI, with real numbers (5,000+ field schemas, the 0.9^5 compounding-error math, GPT-3.5 vs GPT-4 vs Claude latency tradeoffs).",
     "related": ["agent-decision-loop", "footprint-case-file", "rag-deeper", "practice-langgraph"]},

    # ---------------- Tier 4: MLOps & Production ----------------
    {"id": "mlops-practice", "title": "MLOps Practice", "tier": 4, "kind": "md",
     "file": "mlops-practice.md",
     "blurb": "Experiment tracking (MLflow/W&B), model registries, data/model versioning (DVC), CI/CD for ML.",
     "related": ["core-technical", "production-ml", "git-scenarios", "ai-engineer-playbook", "practice-data-engineering"]},
    {"id": "production-ml", "title": "Production ML Practice", "tier": 4, "kind": "md",
     "file": "production-ml-practice.md",
     "blurb": "Batch vs. real-time serving, monitoring, model/data drift, canary deploys, rollback — what happens after training ends.",
     "related": ["mlops-practice", "common-issues", "system-design", "ai-engineer-playbook", "practice-data-engineering"]},

    # ---------------- Tier 5: Interview Performance & Synthesis ----------------
    {"id": "live-coding", "title": "Live Coding Prep", "tier": 5, "kind": "md",
     "file": "live-coding-prep.md",
     "blurb": "Timed problem-solving with the libraries from Tier 0 — the pressure-test of the foundations.",
     "related": ["practice-numpy", "practice-pandas", "practice-utilities", "module-cheatsheet",
                 "leetcode-arrays-strings", "leetcode-dp-trees-graphs"]},
    {"id": "leetcode-sql", "title": "LeetCode SQL", "tier": 5, "kind": "md",
     "file": "leetcode-sql.md",
     "blurb": "40 real problems — joins, self-joins, window functions, subqueries. Memorize-format: problem, solution, one-line why.",
     "related": ["sql-practice", "live-coding"]},
    {"id": "leetcode-pandas", "title": "LeetCode Pandas", "tier": 5, "kind": "md",
     "file": "leetcode-pandas.md",
     "blurb": "35 real problems — filtering, groupby, merge, pivot/melt, string/datetime ops, method chaining.",
     "related": ["practice-pandas", "practice-numpy", "live-coding"]},
    {"id": "leetcode-arrays-strings", "title": "LeetCode Arrays & Strings", "tier": 5, "kind": "md",
     "file": "leetcode-arrays-strings.md",
     "blurb": "60 canonical problems grouped by pattern — two pointers, sliding window, hashmap, stack, binary search, intervals.",
     "related": ["live-coding", "module-cheatsheet"]},
    {"id": "leetcode-dp-trees-graphs", "title": "LeetCode DP, Trees & Graphs", "tier": 5, "kind": "md",
     "file": "leetcode-dp-trees-graphs.md",
     "blurb": "43 problems — dynamic programming, backtracking, tree/graph traversal (BFS/DFS). Recursion is the throughline.",
     "related": ["live-coding", "practice-langgraph"]},
    {"id": "leetcode-stats-probability", "title": "LeetCode Stats/Probability & \"From Scratch\"", "tier": 5, "kind": "md",
     "file": "leetcode-stats-probability.md",
     "blurb": "25 DS-specific problems — reservoir sampling, weighted random pick, implementing train_test_split/k-means/linear regression from scratch.",
     "related": ["practice-stats", "math-foundations", "practice-numpy"]},
    {"id": "leetcode-system-design-structures", "title": "LeetCode Design-a-Data-Structure", "tier": 5, "kind": "md", "role": "ai_engineer",
     "file": "leetcode-system-design-structures.md",
     "blurb": "LRU Cache, Trie, Design Twitter/TinyURL/Rate Limiter, Alien Dictionary, Course Schedule II, Median of Two Sorted Arrays, Word Break II — the 'design a class' coding-round cluster reported most often in AI Engineer loops specifically.",
     "related": ["leetcode-arrays-strings", "leetcode-dp-trees-graphs", "live-coding"]},
    {"id": "system-design", "title": "System Design Prep", "tier": 5, "kind": "md",
     "file": "system-design-prep.md",
     "blurb": "Architecting a full ML system end to end — synthesizes problem framing, LLM systems, and scale tradeoffs.",
     "related": ["problem-formulation", "core-technical", "practice-langgraph", "production-ml", "my-projects", "real-world-incidents", "system-design-drills", "ai-engineer-playbook"]},
    {"id": "system-design-drills", "title": "System Design — Deep Interrogation Drills", "tier": 5, "kind": "md",
     "file": "system-design-deep-drills.md",
     "blurb": "Interviewer-transcript format: one scenario, real numbers, follow-ups that never stop — RAG at 10,000 concurrent users, continuous training on continuous input, real-time fraud detection at 5,000 TPS/50ms, end-to-end pipeline ops, and designing an explainable/debuggable AI agent.",
     "related": ["system-design", "real-world-incidents", "rag-deeper", "production-ml", "mlops-practice", "footprint-case-file", "agent-decision-loop"]},
    {"id": "behavioral", "title": "Behavioral / Partnership STAR Stories", "tier": 5, "kind": "md",
     "file": "behavioral-partnership-star-stories.md",
     "blurb": "STAR stories drawn from real project work — pairs naturally with the technical stories above.",
     "related": ["problem-formulation", "service-impact", "domain-context", "my-projects"]},
    {"id": "my-projects", "title": "My Projects — Architecture, Code & Module Breakdown", "tier": 5, "kind": "md",
     "file": "my-projects-portfolio.md",
     "blurb": "FinSight, NaviDoc, and every other real project on this hub — 3-level zoom (architecture → code → modules), visual, grounded only in facts stated elsewhere here.",
     "related": ["system-design", "behavioral", "core-technical", "domain-context"]},
]

TOPICS_BY_ID = {t["id"]: t for t in TOPICS}
TIERS_BY_ID = {t["id"]: t for t in TIERS}

for _t in TOPICS:
    _t["tier_name"] = TIERS_BY_ID[_t["tier"]]["name"]

# sanity: every related id must point at a real topic
for _t in TOPICS:
    for _r in _t["related"]:
        assert _r in TOPICS_BY_ID, f"{_t['id']} links to unknown topic {_r}"
